[package]
name = "kubutton"
version = "0.1.0"
authors = ["Dan Miller <dmiller@windmill.engineering>"]
edition = "2018"

[dependencies]
serialport = "3.2.0"
reqwest = "0.9.16"

[profile.release]
lto = true
